name = "event-push-notification"
main = "src/index.ts"
compatibility_date = "2024-02-08"
compatibility_flags = [ "nodejs_compat" ]

[placement]
mode = "smart"

[triggers]
crons = ["0 */1 * * *"]

[dev]
ip="localhost"
port = 3000
local_protocol = "http"

[vars]
PUSHBULLET_TOKEN = "{{PUSHBULLET_TOKEN}}"

[[d1_databases]]
binding = "DB"
database_name = "{{DATABASE_NAME}}"
database_id = "{{DATABASE_ID}}"
