name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Prepare wrangler.toml
        run: |
          cp wrangler-example.toml wrangler.toml
          sed -i 's/{{PUSHBULLET_TOKEN}}/${{ secrets.PUSHBULLET_TOKEN }}/g' wrangler.toml
          sed -i 's/{{DATABASE_NAME}}/${{ secrets.DATABASE_NAME }}/g' wrangler.toml
          sed -i 's/{{DATABASE_ID}}/${{ secrets.DATABASE_ID }}/g' wrangler.toml
          sed -i 's/{{CUSTOM_DOMAIN}}/${{ secrets.CUSTOM_DOMAIN }}/g' wrangler.toml
      - name: Deploy to CF Worker
        run: CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} pnpm run deploy
